### ISSUE TITLE
free.fr and mobile.free.fr (remove)

### ISSUE THREAD

**Issue by Catarax** [mrvivacious/PorNo-_Porn_Blocker#41]
French internet operator, blocked for some weird reasons.

**Comment by mrvivacious** [comment]
Hi! Thank u for making this issue. just now getting to it and will submit chrome and android updates soon.
Not sure why that site was blocked -- large parts of my list database were copied from lists found online, didn't spend any time going thru the list lol

√ removed free.fr from `f.txt
√ chrEx loads free.fr without redirecting
