### ISSUE TITLE
ipchicken.com false positive

### ISSUE THREAD

**Issue by cheekyp123** [mrvivacious/PorNo-_Porn_Blocker#48]
ipchicken.com is just a webste that tells you your IP address. No porn here! but im not allowed to access
Thanks for this plugin its really great.

**Comment by mrvivacious** [comment]
Oh! Nice catch! Thank you for reporting :)

I'm very busy for a few weeks with my day job...I plan to release the next update by the end of March :/ 

Hope this isn't too long of a wait 😅 thank you for using PorNo! as well 😄😄

**Comment by mrvivacious** [comment]
Hi,

This website has been removed from the banlist and is now free to visit :)

Thank you for letting me know!

https://github.com/mrvivacious/PorNo-_Porn_Blocker/commit/ab7cd7261ac5d7c1e48336f2203ae599e4b33852#r49837597
