### ISSUE TITLE
[Android app] Add an "Email developer" button 

### ISSUE THREAD

**Issue by mrvivacious** [mrvivacious/PorNo-_Porn_Blocker#61]
**as a** user
**i want** an easy way to email the app developer about problems and unbanned websites
**so that** PorNo! can work better for everyone

work description:
- [x] add button
- [x] set up subject line to say `PorNo! Android`
- [x] test
- [x] publish update

**Comment by mrvivacious** [comment]
add button either in popup menu or in AboutActivity screen

**Comment by mrvivacious** [comment]
https://stackoverflow.com/questions/21720640/sending-email-from-android-app-when-click-on-button

**Comment by realBJ-dot** [comment]
aye im on it.

**Comment by mrvivacious** [comment]
[Resolved](https://github.com/mrvivacious/PorNo-_Porn_Blocker/commit/ed0c629aec638115099db65b245b047b6337df24#diff-e94d13460d652dec4294a5e6e6da5c17262417d2639b47ca3c97c4fec5a1843cR6)!!!! Thank you Barney :D
