### ISSUE TITLE
xes.pl

### ISSUE THREAD

**Issue by altlas-developers** [mrvivacious/PorNo-_Porn_Blocker#75]

**Comment by mrvivacious** [comment]
Hi! Thank u for opening an issue. This site was in the lists but it was not being picked up by the chrEx, more info in #60. PorNo! will now redirect from this site.
Updates for both chrome and android will be submitted this week :D 
THank you again for your help <3 

√ xes.pl is in x.txt
√ chrEx redirects
√ android redirects
